apiVersion: apps/v1
kind: Deployment
metadata:
  name: worklenz-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worklenz-backend
  template:
    metadata:
      labels:
        app: worklenz-backend
    spec:
      containers:
        - name: worklenz-backend
          image: ghcr.io/worklenz/worklenz-backend
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: regcred
