apiVersion: apps/v1
kind: Deployment
metadata:
  name: worklenz-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worklenz-db
  template:
    metadata:
      labels:
        app: worklenz-db
    spec:
      containers:
        - name: db
          image: {{ .Values.db.image }}
          ports:
            - containerPort: {{ .Values.db.port }}
          env:
            {{- range $key, $value := .Values.db.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
